### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by awf** [jakob-bagterp/timer-for-python#28]
https://github.com/jakob-bagterp/timer-for-python/blob/d9500261df566c4d39cc3a3dd28ec6de78665a7c/src/timer/helper/thread/list.py#L6

In 3.8 I need to use `Tuple` here to avoid
```
Traceback (most recent call last):
  File "pure-transformer.py", line 21, in <module>
    from timer import Timer
  File "/home/awf-wsl/envs/jax/lib/python3.8/site-packages/timer/__init__.py", line 4, in <module>
    from .timer import Timer
  File "/home/awf-wsl/envs/jax/lib/python3.8/site-packages/timer/timer.py", line 3, in <module>
    from . import controller
  File "/home/awf-wsl/envs/jax/lib/python3.8/site-packages/timer/controller/__init__.py", line 3, in <module>
    from .. import error
  File "/home/awf-wsl/envs/jax/lib/python3.8/site-packages/timer/error/__init__.py", line 3, in <module>
    from .. import helper
  File "/home/awf-wsl/envs/jax/lib/python3.8/site-packages/timer/helper/__init__.py", line 6, in <module>
    from . import thread
  File "/home/awf-wsl/envs/jax/lib/python3.8/site-packages/timer/helper/thread/__init__.py", line 3, in <module>
    from . import list
  File "/home/awf-wsl/envs/jax/lib/python3.8/site-packages/timer/helper/thread/list.py", line 5, in <module>
    def try_get_thread_item_and_index(timer: TimerObject, thread: str) -> tuple[ThreadItem, int]:
TypeError: 'type' object is not subscriptable
```

**Comment by jakob-bagterp** [comment]
Thank you for the interest in my project, @awf. And for and raising the first ever issue. 🙂

Yes, you're right. The Timer doesn't work with Python version 3.8. Earlier versions aren't supported as I want to use the latest features and optimisations of 3.10 for this project.

However, it would probably be fairly simple to refactor the code to support 3.8. Would that be relevant for you, or did you already upgrade Python to version 3.10?

**Comment by awf** [comment]
Actually I went for an alternative implementation - from this library, I liked the `with timer() as t: ... t.elapsed ...` option, but I don't need it right now.  I'll be sure to look back at this one when I have the need for it :)
